# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:
with builtins;
with lib; let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name {nativeBuildInputs = [zig];} ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig = {
    name,
    url,
    hash,
  }: let
    artifact = fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
    rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
  }: let
    parts = splitString "#" url;
    url_base = elemAt parts 0;
    url_without_query = elemAt (splitString "?" url_base) 0;
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
    ...
  } @ args: let
    parts = splitString "://" url;
    proto = elemAt parts 0;
    path = elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig (
        args
        // {
          url = "http://${path}";
        }
      );
      "git+https" = fetchGitZig (
        args
        // {
          url = "https://${path}";
        }
      );
      http = fetchZig {
        inherit name hash;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
in
  linkFarm name [
    {
      name = "vapoursynth-4.0.0-jLYMQ5ORAgDTNkAckZJ2-VlAfCjJryGPI2WS_YOvoszD";
      path = fetchZigArtifact {
        name = "vapoursynth";
        url = "git+https://github.com/dnjulek/vapoursynth-zig.git#7bb42c377bf8094b3d2c7e398666862094976339";
        hash = "sha256-Y6m2gnNjwMHlZ+tUaLhIQz5X6LTeDxAOk4UhwEfA+sw=";
        rev = "7bb42c377bf8094b3d2c7e398666862094976339";
      };
    }
    {
      name = "zigimg-0.1.0-8_eo2lrXEgBlEihqJdiw_ZtxgL-vO72ajJpmOdO59qxp";
      path = fetchZigArtifact {
        name = "zigimg";
        url = "git+https://github.com/zigimg/zigimg.git#b1c5beea3b200a949fe7edf15ba8317cb9253efe";
        hash = "sha256-URYEpFTkj1oUIgxA48OpKuVJCJ5p6I8QGXsBkPschHU=";
        rev = "b1c5beea3b200a949fe7edf15ba8317cb9253efe";
      };
    }
  ]
