# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}: let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name {nativeBuildInputs = [zig];} ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig = {
    name,
    url,
    hash,
  }: let
    artifact = fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
    rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
  }: let
    parts = lib.splitString "#" url;
    url_base = lib.elemAt parts 0;
    url_without_query = lib.elemAt (lib.splitString "?" url_base) 0;
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
    ...
  } @ args: let
    parts = lib.splitString "://" url;
    proto = lib.elemAt parts 0;
    path = lib.elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig (
        args
        // {
          url = "http://${path}";
        }
      );
      "git+https" = fetchGitZig (
        args
        // {
          url = "https://${path}";
        }
      );
      http = fetchZig {
        inherit name hash;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
in
  linkFarm name [
    {
      name = "vapoursynth-4.0.0-jLYMQw95AgBWLJymsYybHIFxNu7d6shoYn8y8WZfH8T3";
      path = fetchZigArtifact {
        name = "vapoursynth";
        url = "git+https://github.com/dnjulek/vapoursynth-zig.git#a94152c87e4242a582ec5f30f4d4e890c14e2233";
        hash = "sha256-ZhWDmdq15NMBZe9LxM+AhjAT78yI0xNz+My1UOF9mYc=";
        rev = "a94152c87e4242a582ec5f30f4d4e890c14e2233";
      };
    }
  ]
