# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}: let
  fetchZig = {
    name,
    url,
    hash,
  }:
    runCommand "${name}.tar.gz"
    {
      src = url;
      nativeBuildInputs = [zig];
      outputHash = hash;
      outputHashMode = "flat";
    }
    ''
      touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
      hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
      mv "$TMPDIR/p/$hash.tar.gz" "$out"
    '';
in
  linkFarm name [
    {
      name = "vapoursynth-4.0.0-jLYMQw95AgBWLJymsYybHIFxNu7d6shoYn8y8WZfH8T3.tar.gz";
      path = fetchZig {
        name = "vapoursynth";
        url = "git+https://github.com/dnjulek/vapoursynth-zig.git#a94152c87e4242a582ec5f30f4d4e890c14e2233";
        hash = "sha256-bUmdR2iQoS12F+8iwM+q6IZAnnMl4ZYIAhOxfDFvglA=";
      };
    }
  ]
