# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  linkFarm,
  fetchzip,
}:
linkFarm "zig-packages" [
  {
    name = "1220934bee8b3a95746a75dade79b531fba3f8f5ac71161422c5ec79e666b0d8b53f";
    path = fetchzip {
      name = "vapoursynth";
      url = "https://github.com/dnjulek/vapoursynth-zig/archive/7d3484e702dac4cee8310b421af045cabac048ef.tar.gz";
      hash = "sha256-n9r/6VwQamzOFMuVXGUXVaG6lRq8GWdjgNWQ/2z8NzE=";
    };
  }
]
