# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}: let
  fetchZig = {
    name,
    url,
    hash,
  }:
    runCommand "${name}.tar.gz"
    {
      src = url;
      nativeBuildInputs = [zig];
      outputHash = hash;
      outputHashMode = "flat";
    }
    ''
      touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
      hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
      mv "$TMPDIR/p/$hash.tar.gz" "$out"
    '';
in
  linkFarm name [
    {
      name = "vapoursynth-4.0.0-jLYMQ799AgCA8sL5lgewK9acIrAKjs-ByT2pdKI5dHq2.tar.gz";
      path = fetchZig {
        name = "vapoursynth";
        url = "git+https://github.com/dnjulek/vapoursynth-zig#8e93fe3433bb977135f81040bb59d964c58a1cb9";
        hash = "sha256-MkNqPTsPu0bi3V63yzkUX7a6hWvzQrQSwTp2g407dwQ=";
      };
    }
    {
      name = "zig_set_version-0.4.0-VcSFV3xkAAD0iesHfDhPukAR87ncMWYHeYkUe3ZRRoi1.tar.gz";
      path = fetchZig {
        name = "set_version";
        url = "git+https://github.com/ritalin/zig-set-version#1f3cd71ee0867b1f56c7ae421feddad4f85a55ff";
        hash = "sha256-Qyzmhcmi8/owtwiDfJvToY4eZYC558Ybv+p/zO2r/sw=";
      };
    }
  ]
