# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:
with builtins;
with lib; let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name {nativeBuildInputs = [zig];} ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig = {
    name,
    url,
    hash,
  }: let
    artifact = fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
    rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
  }: let
    parts = splitString "#" url;
    url_base = elemAt parts 0;
    url_without_query = elemAt (splitString "?" url_base) 0;
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
    ...
  } @ args: let
    parts = splitString "://" url;
    proto = elemAt parts 0;
    path = elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig (
        args
        // {
          url = "http://${path}";
        }
      );
      "git+https" = fetchGitZig (
        args
        // {
          url = "https://${path}";
        }
      );
      http = fetchZig {
        inherit name hash;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
in
  linkFarm name [
    {
      name = "vapoursynth-4.0.0-AAAAAJR_AQALLLKKoMHn62LyPAXEDaaowbSoD4GhhxWc";
      path = fetchZigArtifact {
        name = "vapoursynth";
        url = "git+https://github.com/dnjulek/vapoursynth-zig.git#94da91b6229a20c1b8d49825773becead339c1e9";
        hash = "sha256-3Ng8JwPpW7xzZV3BzoR4uGSfHW3NCIF1FHW9KBCCnGM=";
        rev = "94da91b6229a20c1b8d49825773becead339c1e9";
      };
    }
    {
      name = "zig_set_version-0.1.0-AAAAADhiAAACHOWv9wUBBMdyVTCCf1OTn5RD2q1TT0t8";
      path = fetchZigArtifact {
        name = "set_version";
        url = "https://github.com/Mikewando/zig-set-version/archive/refs/heads/package-name-workaround.zip";
        hash = "sha256-bPNfCYhehKwixLTrBUVb2fdubrqFtXaoDJ/I9L5BeyE=";
      };
    }
  ]
