# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}: let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name {nativeBuildInputs = [zig];} ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig = {
    name,
    url,
    hash,
  }: let
    artifact = fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
    rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
  }: let
    parts = lib.splitString "#" url;
    url_base = lib.elemAt parts 0;
    url_without_query = lib.elemAt (lib.splitString "?" url_base) 0;
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
    ...
  } @ args: let
    parts = lib.splitString "://" url;
    proto = lib.elemAt parts 0;
    path = lib.elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig (
        args
        // {
          url = "http://${path}";
        }
      );
      "git+https" = fetchGitZig (
        args
        // {
          url = "https://${path}";
        }
      );
      http = fetchZig {
        inherit name hash;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
in
  linkFarm name [
    {
      name = "vapoursynth-4.0.0-jLYMQ799AgCA8sL5lgewK9acIrAKjs-ByT2pdKI5dHq2";
      path = fetchZigArtifact {
        name = "vapoursynth";
        url = "git+https://github.com/dnjulek/vapoursynth-zig#8e93fe3433bb977135f81040bb59d964c58a1cb9";
        hash = "sha256-tcBr4q7/8u/8xmBO2dbtExi3n5j006nh6/fniO37UK4=";
        rev = "8e93fe3433bb977135f81040bb59d964c58a1cb9";
      };
    }
    {
      name = "zig_set_version-0.2.0-VcSFVztkAAC2ZA9vFlkYsvHpDZLNGa9SlhKzuCGlO-10";
      path = fetchZigArtifact {
        name = "set_version";
        url = "git+https://github.com/ritalin/zig-set-version#9fc39eaafd0bfd49090189fc6f772c24c1245c69";
        hash = "sha256-mKoCKY6q0/vFM2PduKS0R7x9cCXlNlwx0+zHX/12yH0=";
        rev = "9fc39eaafd0bfd49090189fc6f772c24c1245c69";
      };
    }
  ]
